version: 3

includes:
  npm_utils: https://raw.githubusercontent.com/Terradue/taskfile-utils/refs/heads/main/npm.yaml
  pip_utils: https://raw.githubusercontent.com/Terradue/taskfile-utils/refs/heads/main/pip.yaml

vars:
  INPUT_API: './openapi.yaml'

tasks:

  openapi_docs:
    desc: Given an input OpenAPI YAML document, creates Redocly human-readable documentation.
    vars:
      OUTPUT: './docs/openapi/index.html'
    deps:
    - task: npm_utils:conditional_install
      vars:
        PACKAGE: '@redocly/cli'
    cmds:
    - redocly build-docs {{.INPUT_API}} --output={{.OUTPUT_DOC}}

  openapi_skeleton:
    desc: Given an input OpenAPI YAML document, creates FastAPI server skeleton with Pydantic v2 models.
    deps:
    - task: pip_utils:conditional_install
      vars:
        PACKAGE: fastapi-code-generator
    cmds:
    - fastapi-codegen --input {{.INPUT_API}} --output {{.OUTPUT_SERVER}} --output-model-type pydantic_v2.BaseModel
