# Copyright 2025 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 3

tasks:

  bundle:
    desc: Given an input OpenAPI YAML document, bundles the API description.
    cmds:
    - |
      npx \
      @redocly/cli \
      redocly \
      bundle \
      {{.API}} \
      --output={{.OUTPUT}} \
      --remove-unused-components \
      --lint-config

  generate_docs:
    desc: Given an input OpenAPI YAML document, creates Redocly human-readable documentation.
    cmds:
    - |
      npx \
      @redocly/cli \
      redocly \
      build-docs \
      {{.API}} \
      --output={{.OUTPUT}}

  generate_skeleton:
    desc: Given an input OpenAPI YAML document, creates FastAPI server skeleton with Pydantic v2 models.
    cmds:
    - |
      uv run \
      --no-cache \
      --with fastapi-code-generator \
      fastapi-codegen \
      --input {{.API}} \
      --output {{.OUTPUT}} \
      --output-model-type pydantic_v2.BaseModel
